# ------------------------------------------------------------------------------
# Copyright 2019 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
base_url = "https://uwe-arzt.de"

title = "Uwes Blog"
description = "projects, thoughts and more"

highlight_code = true
highlight_theme = "css"

generate_theme_css = [
  { theme = "solarized-dark", file = "theme-dark.css" },
  { theme = "solarized-light", file = "theme-light.css" },
]

taxonomies = [
  {name = "categories", paginate_by = 10}
]

compile_sass = true
generate_rss = true

build_search_index = false
