base_url = "https://uwe-arzt.de"

title = "Uwes Blog"
description = "Projects, thoughts and more"

highlight_code = true
highlight_theme = "base16-ocean-dark"

generate_rss = true

build_search_index = false