#!/usr/bin/python
import cgi
import os
import time

# get the needed fields
comment_form = cgi.FieldStorage()

name    = str(comment_form.getvalue("name"))
email   = str(comment_form.getvalue("email"))
comment = str(comment_form.getvalue("comment"))

page    = str(os.getenv('HTTP_REFERER', ''))

# write to file
f = open('comments', 'a')
f.write("-----------------------------------------------\n")
f.write(time.strftime("%d.%m.%Y %H:%M:%S") + "\n")
f.write(page + "\n")
f.write(name + "\n")
f.write(email + "\n")
f.write(comment + "\n")
f.flush()
f.close()



# Forward to page "comment received"
redirect_url = "http://uwe-arzt.de/comment/"
print "Status: 302 Moved"
print "Location: %s" % redirect_url
print
